name: Build MarketStore Image
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: developer
      REGISTRY: ghcr.io/ananthartha
    steps:

    - name: Clone
      uses: actions/checkout@v2

    - name: Install qemu dependency
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Log in to the GitHub Container registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Buildah Build Image
      id: arm64-build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: developer
        tags: latest ${{ github.sha }}
        platform: linux/arm64, linux/amd64
        containerfiles: |
          ./Containerfile

    - name: Push to GitHub Container Repository
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.arm64-build-image.outputs.image }}
        tags: ${{ steps.arm64-build-image.outputs.tags }}
        registry: ${{ env.REGISTRY }}
